service: imagenet-container

provider:
  name: aws
  stage: dev
  region: ap-northeast-1

functions:
  tensorflow-lambda-test:
    image: ${env:AWS_ACCOUNTID}.dkr.ecr.${env:AWS_DEFAULT_REGION}.amazonaws.com/${env:FUNC_NAME}@${env:ECR_DIGEST}
    memorySize: 2048
    timeout: 180
