service: ecr-lambda-test

provider:
  name: aws
  stage: dev
  region: ${env:AWS_DEFAULT_REGION}

functions:
  iconow-predict:
    # ECR のプライベートリポジトリからビルドする
    image: ${env:AWS_ACCOUNTID}.dkr.ecr.${env:AWS_DEFAULT_REGION}.amazonaws.com/${env:FUNC_NAME}@${env:ECR_DIGEST}
    memorySize: 2048
    timeout: 180
