version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.2

executors:
  docker_build:
    machine:
      docker_layer_caching: true

jobs:
  deploy_lambda-test:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-region: ${AWS_REGION}
          aws-access-key-id: ${AWS_ACCESS_KEY_ID_STG}
          aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY_STG}
          override-installed: true
      - run:
          name: env debug
          command: env
      - run:
          name: git clone
          command: |
            git clone https://github.com/kobayashiharuto/lambda-circleci-test.git
            cd lambda-circleci-test
      - run:
          name: aws auth
          command: |
            aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
            aws ecr get-login-password | docker login --username AWS --password-stdin ${AWS_ACCOUNTID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - run:
          name: build image
          command: |
            docker build -t tensorflow-lambda-test .
            docker tag tensorflow-lambda-test ${ACCOUNTID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${FUNC_NAME}
            ECR_DIGEST=`docker push ${AWS_ACCOUNTID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${FUNC_NAME} | grep digest | cut -d ' ' -f3`
            echo &{ECR_DIGEST}
      - run:
          name: serverless deploy
          command: |
            sudo npm install -g serverless
            serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID_STG} --secret ${AWS_SECRET_ACCESS_KEY_STG}
            serverless deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
