version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.2

jobs:
  deploy_lambda_test:
    docker:
      - image: docker
    steps:
      - run:
          name: build image
          command: |
            ps aux
            service --status-all
            service status docker
            service start docker
            docker build -t tensorflow-lambda-test .
      - aws-cli/install
      - aws-cli/setup
      - run:
          name: env debug
          command: env
      - run:
          name: git clone
          command: |
            git clone https://github.com/kobayashiharuto/lambda-circleci-test.git
            cd lambda-circleci-test
      - run:
          name: aws auth
          command: |
            aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
            aws ecr get-login-password | docker login --username AWS --password-stdin ${AWS_ACCOUNTID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - run:
          name: build image
          command: |
            sudo apt-get update --fix-missing
            sudo apt-get install -y apt-transport-https ca-certificates software-properties-common
            sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo apt-key fingerprint 0EBFCD88
            sudo add-apt-repository \
              "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
              $(lsb_release -cs) \
              stable"
            sudo apt-get update
            sudo apt-get install -y docker-ce
            sudo docker --version
            sudo docker --version
      - setup_remote_docker
      - run:
          name: build image
          command: |
            ps aux
            sudo service --status-all
            sudo service status docker
            sudo service start docker
            sudo docker build -t tensorflow-lambda-test .
            sudo docker tag tensorflow-lambda-test ${ACCOUNTID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${FUNC_NAME}
            ECR_DIGEST=`sudo docker push ${AWS_ACCOUNTID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${FUNC_NAME} | grep digest | cut -d ' ' -f3`
            echo &{ECR_DIGEST}
      - run:
          name: serverless deploy
          command: |
            sudo npm install -g serverless
            serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID_STG} --secret ${AWS_SECRET_ACCESS_KEY_STG}
            serverless deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy_lambda_test:
          filters:
            branches:
              only: main
