service: imagenet-container

provider:
  name: aws
  stage: dev
  region: ap-northeast-1

functions:
  hello:
    image: 263839930238.dkr.ecr.ap-northeast-1.amazonaws.com/tensorflow-lambda-test@${env:ECR_DIGEST}
    memorySize: 2048
    timeout: 180
